// app/layout.ts
import { Metadata } from "next";
// import {createContext, useState} from "react";
import { ErrorWrapper } from "./error-wrapper";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: {
    default: "Nextjs Tutotial - Divya Prakash",
    template: "%s | Divya Prakash",
    absolute: "",
  },
  description: "Generated by nextjs"
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body>
        <main>
          <ErrorWrapper>
            {children}
          </ErrorWrapper>
        </main>
        <footer>footer</footer>
      </body>
      </ThemeProvider>
    </html>
  );
}
