// app/layout.ts
import { Metadata } from "next";
import Link from "next/link";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Nextjs Tutotial - Divya Prakash",
    template: "%s | Divya Prakash",
    absolute: "",
  },
  description: "Generated by nextjs"
}


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          <ErrorWrapper>
            {children}
          </ErrorWrapper>
        </main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
