export const metadata = {
    title:'Nextjs',
    description : 'Generated by Next.js'
}

export default function MarketingLayout({children}:{children:React.ReactNode}){
    return (
        <html lang="en">
            <body>
                <header
                style={{
                    backgroundColor:"lightblue",
                    padding:"1rem"
                }}
                >
                    header
                </header>

                <main>
                    {children}
                </main>

                <footer
                style={{
                    backgroundColor:"ghostwhite",
                    padding:"1rem"
                }}>
                    footer
                </footer>
            </body>
        </html>
    )
}