import React from 'react'
import { Suspense } from "react";

import { Metadata } from "next";


export const metadata:Metadata = {
  title:{
    absolute:"Blog",
  },
  description:"Generated by nextjs"
}



export default async function blog() {
 await new Promise((resolve)=>{
  setTimeout(() => {
    resolve("Intentional delay")
  }, 2000);
  })
  // throw new Error("Blog data failed to load")
  return (
    <div>
      {/* <Suspense fallback={<BlogLoader/>}> */}
        blog
      {/* </Suspense> */}
    </div>
  )
}




// function BlogLoader() {
//   return <p>Loading blog posts...</p>;
// }

// function ProfileLoader() {
//   return <p>Loading profile...</p>;
// }

// function ReviewsLoader() {
//   return <p>Loading reviews...</p>;
// }